- salesforceName: "AMER-Canada"
  label: "region-canada"
  approvers:
    - "@nickliffen" # This person gets notified with extention requests, when override is set to true, so ensure the first person is the actual ASE in the region.
    - "@nickliffenOne"
  override: false
- salesforceName: "AMER-Enterprise-Central"
  label: "region-central"
  approvers:
    - "@niro" # This person gets notified with extention requests, when override is set to true, so ensure the first person is the actual ASE in the region.
    - "@niroTwo"
  override: true