name: 'Find People to Notify Per Region'
author: 'NickLiffen'
description: 'A region that parses the object from Salesforce and spits out people to notify'
inputs:
  issueBody:
    description: 'The body of the GitHub Issue which Salesforce Raised'
    required: true
  fileURI:
    description: 'The relative URI path to the yml file storing approvals and notifications people'
    required: true
outputs:
  labelOfRegionToAssignToIssue:
    description: 'The region label to be assigned to the issue'
  githubHandlesOfPeopleToBeNotified:
    description: 'The GitHub handles who should be notified'
  override:
    description: 'Wether the ASE approval can be overriden'
  singleASE:
    description: 'The GitHub handle of the first ASE in the list'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'target'  
  color: 'blue'