name: "Tests"
on: [push]
jobs:
  integ:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Test to see if it works
        id: test
        uses: ./
        with:
          issueBody: "### Region proof of concept being driven from\n\nAMER-Enterprise-Central\n\n### Sales"
          fileURI: ".github/workflows/example-inputs/file.yml"
      - name: See Results
        run: |
          echo ${{ steps.test.outputs.labelOfRegionToAssignToIssue }}
          echo ${{ steps.test.outputs.githubHandlesOfPeopleToBeNotified }}
